import { initScroll, initCursor, initSplitCopy, initNavTheme, tilt } from "./core";
import { initPreloader } from "./preloader";
import { initMenu } from "./menu";
import { initParticleLogo } from "./particles";
import { initMotion } from "./motion";
import { initFeatures, initWhiteLabel, initDevices, initFaq, initPhases, initMarquees, initTabs } from "./sections";

initScroll();
initCursor();
const heroDelay = initPreloader();
document.documentElement.dataset.heroDelay = String(heroDelay);
initSplitCopy(heroDelay);
initMenu();
initNavTheme();
tilt(document.querySelector(".fx-particles"), document.querySelector(".fx-particles-title"), 8);
initParticleLogo(document.querySelector<HTMLCanvasElement>("#fx-particle-canvas"));
initFeatures();
initWhiteLabel();
initTabs();
initDevices();
initFaq();
initPhases();
initMarquees();
initMotion();
document.documentElement.classList.add("fx-ready");
